ALTER TABLE public.golf_courses
  ADD COLUMN IF NOT EXISTS tee1_name TEXT DEFAULT 'ティー1',
  ADD COLUMN IF NOT EXISTS tee2_name TEXT DEFAULT 'ティー2',
  ADD COLUMN IF NOT EXISTS tee3_name TEXT DEFAULT 'ティー3',
  ADD COLUMN IF NOT EXISTS tee4_name TEXT DEFAULT 'ティー4';
